x-common-config: &common
  restart: unless-stopped
  networks:
    - inception

x-bind-volumes: &bind-volumes
  type: bind
  source: ~/data/wordpress
  target: /var/www/html
  bind:
    create_host_path: true

services:

  mariadb:
    build: ./requirements/mariadb
    image: inception-mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      DB_DATABASE : "${MARIADB_DATABASE}"
      DB_HOSTNAME : "${MARIADB_HOSTNAME}"
      DB_USER : "${MARIADB_USER}"
      DB_PASSWORD : "${MARIADB_PASSWORD}"
      DB_ROOT_PASSWORD : "${MARIADB_ROOT_PASSWORD}"
      DB_DATADIR: "${MARIADB_DATADIR}"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p${MARIADB_ROOT_PASSWORD}"]
      interval: 1m30s
      timeout: 15s
      retries: 3
      start_period: 30s
    volumes: 
      - <<: *bind-volumes
        source: ~/data/mariadb/
        target: ${MARIADB_DATADIR}
    <<: *common

  wordpress:
    build: ./requirements/wordpress/
    image: inception-wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    environment:
      MARIADB_DATABASE : "${MARIADB_DATABASE}"
      MARIADB_HOSTNAME : "${MARIADB_HOSTNAME}"
      MARIADB_USER : "${MARIADB_USER}"
      MARIADB_PASSWORD : "${MARIADB_PASSWORD}"
      WP_ADMIN : "${WP_ADMIN}"
      WP_ADMIN_PASSWORD : "${WP_ADMIN_PASSWORD}"
      WP_USER : "${WP_USER}"
      WP_USER_PASSWORD : "${WP_USER_PASSWORD}"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - <<: *bind-volumes
    <<: *common

  nginx:
    build: ./requirements/nginx/
    image: inception-nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - <<: *bind-volumes
    <<: *common
  
  redis:
    build: './bonus/redis/'
    image: inception-redis
    ports:
      - "6379:6379"
    <<: *common

networks:
  inception:
    driver: bridge